export const routes = {
  root: "/",
  manageEmployees: "/manage-employees",
  profile: "/profile",
  myBoard: "/my-board",
  tasks: "/tasks",
  login: "/login",
  register: "/user-register",
  roleList: "/roles",
  role: "/role",
  employee: "/employee",
  viewEditProject: "/project",
  projectList: "/projects",
  task: "/task",
  termsConditions: "terms-and-conditions",
};
