export const routes = {
  root: "/",
  manageEmployees: "/manage-employees",
  profile: "/profile",
  myBoard: "/my-board",
  tasks: "/tasks",
  login: "/login",
  register: "/user-register",
  projectSettings: "/project",
  roleList: "/roles",
  role: "/role",
  employee: "/employee",
  addProject: "/project/add",
  viewEditProject: "/project",
  projectList: "/projects",
};
