const strings = {
  title: "Title",
  dueDate: "Due Date",
  status: "Status",
  actions: "Actions",
  description: "Description",
  addNewTask: "Add New Issue",
  newTask: "Create Issue",
  editTask: "Update Issue",
  taskList: "Issue List",
  myBoard: "My Board",
  manageEmployees: "Manage Employees",
  filter: "filter",
  filterTask: "Filter Issue",
  search: "Search",
  clearFilter: "Clear Filter",
  submit: "submit",
  reset: "reset",
  titleMaxLengthEror: "Title cannot be more than 100 characters",
  descriptionMaxLengthEror: "Description cannot be more than 400 characters",
  titleRequiredError: "Title is required",
  dateError1: "Date must be between",
  and: "and",
  assignedTo: "Assigned To",
  taskId: "Issue Id",
  assignedToRequiredErrror: "Assignee is Required",
  logoText: "Takverse.com",
  deleteTaskHeader: "Delete Issue ?",
  deleteTaskSubHeading1: "Are you sure you want to delete this Issue?",
  deleteTaskSubHeading2: "This action cannot be undone.",
  confirmText: "Confirm",
  cancelText: "Cancel",
  notAuthorizedHeader: "403 - Not Authorized",
  notAuthorizedSubHeader: "You don't have permission to access this page",
  backHome: "Back to Home",
  backToLogin: "Back to Login screen",
  filterInputText: "🔍 Search issues",
  onlyMyIssues: "Only My Issues",
  clearAll: "Clear All",
  somethingWentWrong: "Something went wrong",
  notAuthorizedError: "You are not authorized to access this feature",
};

export default strings;
