const strings = {
  title: "Title",
  dueDate: "Due Date",
  title: "Title",
  status: "Status",
  actions: "Actions",
  description: "Description",
  addNewTask: "Add New Task",
  newTask: "New Task",
  editTask: "Update Task",
  taskList: "Task List",
  myBoard: "My Board",
  manageEmployees: "Manage Employees",
  filter: "filter",
  filterTask: "Filter Task",
  search: "Search",
  clearFilter: "Clear Filter",
  submit: "submit",
  reset: "reset",
  titleMaxLengthEror: "Title cannot be more than 100 characters",
  descriptionMaxLengthEror: "Description cannot be more than 400 characters",
  titleRequiredError: "Title is required",
  dateError1: "Date must be between",
  and: "and",
  assignedTo: "Assigned To",
  taskId: "Task Id",
  assignedToRequiredErrror: "Assignee is Required",
};

export default strings;
