name: build
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Frontend Image
        run: docker build -t task-management-ui .
